version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      MrykI5FR1xS4bS2jU5juSTuUDKdQUQbf8Ddl1tBABQbZ9Y5A5+5Lnib7hqU/YJMjw818IjECTV/KqGv82WZ3C3jMOSAwj1W6h6Ak84c4h2DuYw6Z0aRgpoMi8PdxcOAtDAHR9Hc+24wYkqKCD2aP3c+NAB+FOX41D9hURKLYq08=
